### ISSUE TITLE
Persist Auth Token

### ISSUE THREAD

**Issue by jstart** [tonyli508/LinkedinSwift#9] opened 2016-09-15 03:50 UTC
Love the project, would love to have the ability to persist authentication across launches.  Do you think this would be relatively simple to support?

**Comment by tonyli508** [comment] 2016-09-15 08:11
Persisting the token would be very simple. The problem is how to verify it, if user login on another device your current token will be invalid. 

I could add a `persisted token` init parameter for LinkedinSwiftHelper, who want to persist token could reuse the token across launches. But it sounds like kick the ball to someone else.

**Comment by tonyli508** [comment] 2016-10-20 11:13
Hi @jstart ,

Check  [1.7.4](https://github.com/tonyli508/LinkedinSwift/releases/tag/1.7.4) out, see if this is what you want.

```ruby
pod 'LinkedinSwift', '~> 1.7.4'
```

**Closed** 2016-10-21 21:57 UTC
Labels: question
